---
title: "Covid19 Vaccine Study Final2023"
author: "Tyler Hamblin"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalDat <-read.csv(file="final.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalDat  %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))

male = filter(FinalData, sex =="M")
female = filter(FinalData, sex =="F")
lgbtq = filter(FinalData, LGBTQ =="gay")
drugUser = filter(FinalData, DrugUser =="yes")

```

# Introduction

A new  preventative vaccine (covid921) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of sub populations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.


$H_0$ : The data for the preventative vaccine has no statistical significance to changing infection rate across the listed sub populations. 


$H_A$ : The data for the preventative vaccine does have statistical significance in how it prevents infection for each sub group. 



# Methods


# Results

## Males

### Graphical Results


### Numerical Results


### Inferential Results


### Confidence Interval


## Females

### Graphical Results


### Numerical Results


### Inferential Results


### Confidence Interval


## LGBTQ

### Graphical Results


### Numerical Results


### Inferential Results


### Confidence Interval


## Druggies

### Graphical Results


### Numerical Results


### Inferential Results


### Confidence Interval



# Overall Results and Conclusions






